### ISSUE TITLE
Update to latest

### ISSUE THREAD

**Issue by Alex-Dobrynin** [eman1986/Flipboard.FLAnimatedImage.Xamarin#1]
Please, Update to the latest

**Comment by eman1986** [comment]
1.0.16 is the latest version tag of that library, I'm not seeing a newer version available.

**Comment by Alex-Dobrynin** [comment]
ok, may be there is no new build, but I saw merged pr with support of 120Hz displays. possible there will be new build soon

**Comment by eman1986** [comment]
Once they make a new version tag I will, but I don't grab anything that's just in their main repository.
